language: ruby
script: 'bundle exec rake db:create && rake db:migrate && bundle exec rspec spec/'
rvm:
  - 2.0.0
env:
  - DB=sqlite
notifications:
  email:
    fusion94@gmail.com
# whitelist
branches:
  only:
    - master
